object Version {
   const val coreKtx = "1.12.0"
   const val appcompat = "1.6.1"
   const val material = "1.11.0"
   const val lifecycleRuntimeKtx = "2.7.0"
   const val activityCompose = "1.8.2"
   const val compose = "2023.03.00"
   const val composeUi = "1.6.4"
   const val composeUiGraphics = "1.6.4"
   const val composeUiToolingPreview = "1.6.4"
   const val composeMaterial3 = "1.2.1"
   const val navigationCompose = "2.7.7"
   const val composeUiTooling = "1.3.0"
   const val composeTestJunit4 = "1.6.4"
   const val composeUiTestManifest = "1.6.4"
   const val lifecycleViewModelKtx = "2.7.0"

   const val hilt = "2.48"
   const val hiltCompiler = "1.0.0-alpha01"
   const val hiltNavigationCompose = "2.7.7"
}